name: aws-cfn-deploy-action
description: AWS Cloudformation deploy with state handling
inputs:
  template:
    description: Cloudformation Template
    required: true
    default: cfn-template-yml
  stack-name:
    description: Cloudformation Stack Name
    required: true
  capabilities:
    description: Cloudformation capabilities (Cap0 Cap1 ...)
    required: false
  parameters:
    description: Cloudformation Template Parameters (Key0=Value0 Key1=Value1 ...)
    required: false
  never-fail:
    description: Always pass the step, even if the deployment fails
    required: false
  debug:
    description: Enables debug logs
    required: false
outputs:
  stack-status:
    description: the stack status upon completion
  message:
    description: the stack error message
runs:
  using: node12
  main: index.js
