name: test

on:
  push:
    branches:
      - master

jobs:
  test-validation-failure:
    name: Test validation failure

    runs-on: ubuntu-latest

    outputs:
      status: ${{ steps.deploy.outputs.status }}
      message: ${{ steps.deploy.outputs.message }}

    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: custom action
        id: deploy
        uses: ./
        id: test
        with:
          template: cfn-template-fail-validation.yml
          stack-name: aws-cfn-deploy-action-test
          parameters: Environment=Dev
          debug: true

  test-deployment-failure:
    if: always()

    needs:
      - test-validation-failure

    name: Test deployment failure

    runs-on: ubuntu-latest

    outputs:
      status: ${{ steps.deploy.outputs.status }}
      message: ${{ steps.deploy.outputs.message }}

    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: custom action
        uses: ./
        id: test
        with:
          template: cfn-template-fail-deploy.yml
          stack-name: aws-cfn-deploy-action-test
          parameters: Environment=Dev
          debug: true

  test-success:
    if: always()

    needs:
      - test-deployment-failure

    name: Test successful deployment

    runs-on: ubuntu-latest

    outputs:
      status: ${{ steps.deploy.outputs.status }}
      message: ${{ steps.deploy.outputs.message }}

    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: custom action
        uses: ./
        id: test
        with:
          template: cfn-template-ok.yml
          stack-name: aws-cfn-deploy-action-test
          parameters: Environment=Dev
          debug: true

  consolidate:
    if: always()

    needs:
      - test-validation-failure
      - test-deployment-failure
      - test-success

    name: Consolidate test results

    runs-on: ubuntu-latest

    steps:
      - name: check test results
        run: |
          echo "test-validation-failure"
          echo "status: ${{ needs.test-validation-failure.outputs.status }}"
          echo "message: ${{ needs.test-validation-failure.outputs.message }}"
          echo "test-deployment-failure"
          echo "status: ${{ needs.test-deployment-failure.outputs.status }}"
          echo "message: ${{ needs.test-deployment-failure.outputs.message }}"
          echo "test-success"
          echo "status: ${{ needs.test-success.outputs.status }}"
          echo "message: ${{ needs.test-success.outputs.message }}"
