name: test

on:
  push:
    branches:
      - master

jobs:
  test-validation-failure:
    name: Test validation failure

    runs-on: ubuntu-latest

    outputs:
      stack-status: ${{ steps.deploy.outputs.stack-status }}
      message: ${{ steps.deploy.outputs.message }}

    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: custom action
        id: deploy
        uses: ./
        with:
          template: cfn-template-fail-validation.yml
          stack-name: aws-cfn-deploy-action-test
          parameters: Environment=Dev
          never-fail: true
          debug: true

      - name: check results
        run: |
          if [ "${{ steps.deploy.outputs.stack-status }}" -ne "" ]; then
            exit 1
          fi
          if [ "${{ steps.deploy.outputs.message }}" -ne "Template format error: Unresolved resource dependencies [NonExistingParameter] in the Resources block of the template" ]; then
            exit 1
          fi

  test-deployment-failure:
    needs:
      - test-validation-failure

    name: Test deployment failure

    runs-on: ubuntu-latest

    outputs:
      stack-status: ${{ steps.deploy.outputs.stack-status }}
      message: ${{ steps.deploy.outputs.message }}

    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: custom action
        id: deploy
        uses: ./
        with:
          template: cfn-template-fail-deploy.yml
          stack-name: aws-cfn-deploy-action-test
          parameters: Environment=Dev
          never-fail: true
          debug: true

      - name: check results
        run: |
          if [ "${{ steps.deploy.outputs.stack-status }}" -ne "ROLLBACK_COMPLETE" ]; then
            exit 1
          fi
          if [ "${{ steps.deploy.outputs.message }}" -ne "Stack aws-cfn-deploy-action-test deployment failed" ]; then
            exit 1
          fi

  test-success:
    needs:
      - test-deployment-failure

    name: Test successful deployment

    runs-on: ubuntu-latest

    outputs:
      stack-status: ${{ steps.deploy.outputs.stack-status }}
      message: ${{ steps.deploy.outputs.message }}

    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: custom action
        id: deploy
        uses: ./
        with:
          template: cfn-template-ok.yml
          stack-name: aws-cfn-deploy-action-test
          parameters: Environment=Dev
          debug: true

      - name: check results
        run: |
          if [ "${{ steps.deploy.outputs.stack-status }}" -ne "CREATE_COMPLETE" ]; then
            exit 1
          fi
          if [ "${{ steps.deploy.outputs.message }}" -ne "" ]; then
            exit 1
          fi

  clean:
    if: always()

    needs:
      - test-success

    name: Delete stack

    runs-on: ubuntu-latest

    steps:
      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: delete stack
        run: aws cloudformation delete-stack --stack-name aws-cfn-deploy-action-test

  consolidate:
    if: always()

    needs:
      - test-validation-failure
      - test-deployment-failure
      - test-success

    name: Consolidate test results

    runs-on: ubuntu-latest

    steps:
      - name: check test results
        run: |
          echo "test-validation-failure"
          echo "stack-status: ${{ needs.test-validation-failure.outputs.stack-status }}"
          echo "message: ${{ needs.test-validation-failure.outputs.message }}"
          echo "test-deployment-failure"
          echo "stack-status: ${{ needs.test-deployment-failure.outputs.stack-status }}"
          echo "message: ${{ needs.test-deployment-failure.outputs.message }}"
          echo "test-success"
          echo "stack-status: ${{ needs.test-success.outputs.stack-status }}"
          echo "message: ${{ needs.test-success.outputs.message }}"
